### ISSUE TITLE
[FFox] Account config is not persisted

### ISSUE THREAD

**Issue by chris-aeviator** [bumi/lightning-browser-extension#13]
After setting up an account I can see the account details & config displayed in the options window of the extension.

![image](https://user-images.githubusercontent.com/11522213/112283983-00659e80-8c89-11eb-811f-c5c8052c6b6d.png)

When trying to use the account to pay, webln reports `err, provider No account available`.
When returning to the account options, the account config seems not to be persisted

![image](https://user-images.githubusercontent.com/11522213/112284334-69e5ad00-8c89-11eb-8565-369d0671c477.png)

```
{
  "currentKey": "e3c6b9ac4ccae3f063a4c4c1a9b464a8bb60413de200e60457b638c6e27834d0",
  "accounts": {}
}
```

The account config should be persisted.

**Comment by bumi** [comment]
I've removed options sync there and refactored the account/allowances storage: #14 
can we test it with that change again.

**Comment by chris-aeviator** [comment]
fixed with https://github.com/bumi/lightning-browser-extension/pull/14
