### ISSUE TITLE
Implement Unlock Screen

### ISSUE THREAD

**Issue by chris-aeviator** [bumi/lightning-browser-extension#16]
Should be  a password field 
Viewport should be bigger

**Comment by bumi** [comment]
related to #1 

To open use the configured account we need to decrypt the stored account details (unlock the account). 
This is the first step when opening the popup.

**Comment by chris-aeviator** [comment]
Bitwarden (Open Source Password manager, https://bitwarden.com/) displays the extensions icon differently depending on if it's in locked or unlocked state. Since computers might be shared this could be benefitial to the user.

## Unlocked 
![grafik](https://user-images.githubusercontent.com/11522213/112750710-7be98780-8fca-11eb-8eda-2cd96bb3f975.png)

## Locked
![grafik](https://user-images.githubusercontent.com/11522213/112750735-94f23880-8fca-11eb-95e3-2d15e3950454.png)
