### ISSUE TITLE
Display preimage on transaction list

### ISSUE THREAD

**Issue by bumi** [bumi/lightning-browser-extension#214]
The user should be able to access the preimage of each payment in the transaction list. 

This should be possible by adding the preimage to: https://github.com/bumi/lightning-browser-extension/blob/master/src/app/components/TransactionsTable/index.tsx#L45

The preimage is already stored in the payments (https://github.com/bumi/lightning-browser-extension/blob/master/src/extension/background-script/db.js#L11)

**Comment by lejara** [comment]
Hello!

Is it okay if i can work on this?

If yes,
how do you want it styled?

**Comment by bumi** [comment]
Hey @lejara! yay, that's would be great! 

I think we can add it to the `subtitle` of the transaction or add a new similar row after that? (https://github.com/bumi/lightning-browser-extension/blob/master/src/app/components/TransactionsTable/index.tsx#L54-L56)

maybe you can try it and then @johnsBeharry can have a look and we can iterate on it? 

let me know if you need  help.

**Comment by lejara** [comment]
Cool! 
I added it under the subtitle. Though I think best to add in a drop down within the transaction. Since preimages are referred as secrets, up to you all.

https://github.com/lejara/lightning-browser-extension/commit/16dd91b69365659de1b7ed3695a383cd82e7d69a



![preimage_under_subtile](https://user-images.githubusercontent.com/16671822/132703825-899f98f7-3266-4939-a78f-c9303c180053.JPG)

**Comment by bumi** [comment]
yeah, that's already great and helpful. feel free to open a pull request.
How would you do the dropdown? 
Maybe we could also indicate that it is the preimage and maybe also make the font smaller? 

@johnsBeharry do you have any design thoughts?

**Comment by lejara** [comment]
Just by adding a chevron...

Closed:
![dropdown_close](https://user-images.githubusercontent.com/16671822/132933679-d83679b0-39da-470a-b270-84d98bc0e30c.jpg)

Open:
![dropdown_open](https://user-images.githubusercontent.com/16671822/132933686-386a03c5-b127-421b-90b3-fb06f97f9468.jpg)

And yeah indicating its a preimage seems like a good idea! I can add it.

Other than that if your okay with everything, i will open a pull request.

**Comment by bumi** [comment]
I think that's a great idea. Maybe we can move the whole details behind that?

**Comment by johnsBeharry** [comment]
Welcome @lejara thanks for your interest in the project!

I'm all for moving fast and fixing things at this stage so I wouldn't want to be a blocker on this. stylistically the chevron could be a lot smaller. The dependency "@bitcoin-design/bitcoin-icons" should have "Icon/Caret down". 

<img width="599" alt="Screenshot 2021-09-13 at 14 08 38" src="https://user-images.githubusercontent.com/183140/133080822-648cf019-8144-4d63-97ee-1fc6102f2635.png">

> The user should be able to access the preimage of each payment in the transaction list.

@bumi could you give me some more context on how* someone would need to retrieve the pre-image while using the extension?

**Comment by johnsBeharry** [comment]
@bumi since this is on the allowance page, of a specific publisher, why is the url also shown in the tx list? theres lots of repetition going on there.

**Comment by bumi** [comment]
The user might need to copy and paste that preimage to proof the payment or to do things like decrypting content with that. 
Guess this is a bit more advanced and not always needed but we should show it.... so I like the idea to put it behind a click.


The URL that is shown in that list is the full page URL (with path) - we do not show this otherwise currently.

**Comment by johnsBeharry** [comment]
I think the title, time and amounts are the primary things to show in the list. the more details can show the url imo.

otherwise its just so messy.

**Comment by bumi** [comment]
@lejara made a great PR there, doing also what @johnsBeharry suggests
