### ISSUE TITLE
Source Map configuration

### ISSUE THREAD

**Issue by motorina0** [bumi/lightning-browser-extension#23]
I'm new to React, sorry if this already explained/configured somewhere else.

We need to have the Source Code visible in the Browser console so we can easily locate errors.
Currently the stack trace is for the generated JS file (hard to read).

I've added the default configs for sourcemaps in this PR https://github.com/bumi/lightning-browser-extension/pull/22
But it still does not give me the friendly source code.

See #20 for current stack trace.

**Comment by bumi** [comment]
should also get an update in #37 - can you confirm that it works for you?

**Comment by motorina0** [comment]
Works like a charm, thanks!
![image](https://user-images.githubusercontent.com/2951406/114369037-a882cf00-9b86-11eb-98bf-2fb3c9499a27.png)
