### ISSUE TITLE
[LND Client] HTTP REST vs GRPC generated from proto

### ISSUE THREAD

**Issue by motorina0** [bumi/lightning-browser-extension#27]
Currently the LND client uses REST over HTTP.  This approach works, but there is a lot of overhead in handling the communication.

The alternative is to use `gRPC`.
By using `gRPC` we get all the LND APIs out of the box with minimal configuration.

> gRPC-generated stubs and skeletons hide HTTP from the client and server too, so nobody has to worry how the RPC concepts are mapped to HTTP

LND supports `gRPC`:
  - https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/javascript.md

The `gRPC` API is well documented:
  - https://api.lightning.community/?javascript#subscribesingleinvoice

It is a low effort to replace it since I have already created a client on a boilerplate project that I'm building:
  - https://github.com/motorina0/node-express-postgres-ln-boilerplate/blob/issue_1/src/ln/client/index.js

Sphinx_chat also uses gRPC for LND

### Question:
 - is it OK to replace the current REST API with gRPC for the LND connection?

**Comment by chris-aeviator** [comment]
@motorina0 will we have to supply the certificate clientside?

**Comment by motorina0** [comment]
Good point!
Yes, from  what I can tell so far the `.cert` is mandatory.

**Comment by bumi** [comment]
The big (unsolvable?) problem is that gRPC does NOT work in the browser and thus we can not use that in the extension. 
At least it does not work without any grpc-web support on the server side.

That is the reason why we have to use the REST API when we directly want to connect to a LND node.

To work around those limitations the idea was to use a native companion app and talk to that native app using [native messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) (see the [native connector](https://github.com/bumi/lightning-browser-extension/blob/master/source/lib/connectors/native.js) and [lnd-native-companion](https://github.com/bumi/lnd-native-companion)).

The native extension also works around the problem with self-signed certificates for the REST API. (which also do not work in the browser)


This native app could for example also be an existing app like [zap](https://zaphq.io/).

**Comment by bumi** [comment]
I think maybe we should leave this one around? maybe we come up with a solution somehow? or the grpc-web stuff is somehow possible at some point?

**Comment by motorina0** [comment]
Not much new info in this issue. We can re-open/reference it when/if we revisit gRPC.
Otherwise I'm afraid we will have hundreds of open issues like this :)

**Comment by bumi** [comment]
yep, true. you're right.
