### ISSUE TITLE
Support for react-dev tools

### ISSUE THREAD

**Issue by bumi** [bumi/lightning-browser-extension#31]
For development the react-dev tools are quite handy. 
Seems it is not straight forward to use those in an extension. 
see: https://github.com/abhijithvijayan/web-extension-starter/issues/51

How does it work for us?

**Comment by motorina0** [comment]
This works for us:
  - install `react-devtools` globally
  - start `react-devtools`
    -  ![image](https://user-images.githubusercontent.com/2951406/114145021-a3234b80-991e-11eb-8074-2811fc76d22c.png)
  - update `configs` and `html` page. See changes in this commit: https://github.com/bitcoincoretech/lightning-browser-extension/commit/23977691ef486bac07d186370193701fa1f2d08b
  - open extension page. reaxt-devtool should show this now:
    -  ![image](https://user-images.githubusercontent.com/2951406/114145413-07dea600-991f-11eb-9b76-1ad3dcf1d53f.png)

**Comment by motorina0** [comment]
**Challenge**: do net let the debug config get into the prod build

**Comment by chris-aeviator** [comment]
> **Challenge**: do net let the debug config get into the prod build

maybe having a test that checks `manifest.json` or having a `manifest.development.json` & `html`?

**Comment by chris-aeviator** [comment]
@motorina0 

getting these warnings

![image](https://user-images.githubusercontent.com/11522213/114160182-f0a3b680-9926-11eb-8dd6-fdbf8896bdeb.png) with https://github.com/bitcoincoretech/lightning-browser-extension/commit/23977691ef486bac07d186370193701fa1f2d08b

**Comment by chris-aeviator** [comment]
according to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy#invalid_examples `http` is not supported in a FF web-extension manifest

**Comment by bumi** [comment]
maybe also some inspiration from the metamask extension: https://github.com/MetaMask/metamask-extension#development-builds

**Comment by bumi** [comment]
anybody knows what the status here is? do we still need this?

**Comment by abhijithvijayan** [comment]
@bumi I have updated the existing solution in my repo issue to use a new plugin to use with the html plugin.

what it does it, it takes care of the injection of `<script>` tag needed for React DevTools in the html files generated automatically for when NOT IN NODE_ENV === production`. The manifest entry could use the prefixed `__dev__` & `__prod__` entry to only permit that script in development.

Follow https://github.com/abhijithvijayan/web-extension-starter/issues/51#issuecomment-727558039 this if you guys still need the solution for this in a clean way.

Thanks :p
