### ISSUE TITLE
Add "Test" functionality for the LND account type

### ISSUE THREAD

**Issue by motorina0** [bumi/lightning-browser-extension#39]
- Test end-2-end connection
- Show public key
- [ ] unlock wallet if needed?

**Comment by bumi** [comment]
For the welcome wizard @johnsBeharry had proposed a [two step process](https://www.figma.com/file/xEPJFGFdc3HD0JS1ax2IpH/Lightning-Browser-Extension): 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/318/114226119-78afad80-9973-11eb-8ec5-02070472db4f.png">


I was wondering if we should apply that also for the options settings here. Then we would always "test" the connection first, show connection details (e.g. wallet alias, balance, etc.) or an error and allow the user to confirm and save the account.

**Comment by chris-aeviator** [comment]
we've had the discussion to use redux for state management. maybe it's good to check the store if we have a value already instead of doing the same queries multiple times

**Comment by motorina0** [comment]
The UI looks really nice! It makes sense to use the same screen on the Options page (not two different ones).

**Comments**:
  - add select connector/account type (LND, c-lightining, etc)
  - connections success (amount area) should not be in red (reserved for error)
  - how easy is to customize `antd` to have this specific look&feel?
     -  I have asked @muntianrazvan to analyze the pros/cons of this extra UI lib

**Comment by bumi** [comment]
my thoughts around antd:
I am not very experienced with antd. 
From the feedback I got so far it seems to be a pretty good, flexible library with good and customizable standard components. Also Joule uses it and we might be able to learn from there. 

In the current stage I was search for something that can help us to quickly iterate and experiment with the UX.

**Comment by motorina0** [comment]
- [ ] add UUID to accounts (do not use name as key)
- [ ] it should not be the responsibility of the `connectors` to do `lock`, `unlock`, `isLocked`, but instead the `storage` service should take care of this

**Comment by motorina0** [comment]
![image](https://user-images.githubusercontent.com/2951406/115379290-0f813300-a1da-11eb-907c-30f9bf0a4210.png)

![image](https://user-images.githubusercontent.com/2951406/115379349-20ca3f80-a1da-11eb-8b9b-6ccf457989cc.png)

![image](https://user-images.githubusercontent.com/2951406/115379393-29227a80-a1da-11eb-8a2a-9ca8c75057ec.png)

![image](https://user-images.githubusercontent.com/2951406/115379424-30498880-a1da-11eb-96d8-52e01e0a1bca.png)

![image](https://user-images.githubusercontent.com/2951406/115379502-40f9fe80-a1da-11eb-879a-e9b0b312a592.png)

**Comment by chris-aeviator** [comment]
We have multi account capabilities now ? :heart:
