### ISSUE TITLE
Payment confirmation prompt

### ISSUE THREAD

**Issue by bumi** [bumi/lightning-browser-extension#4]
The confirmation prompt is shown whenever a website requests a payment from the user (and the user does not have an allowance configured)

We need to show the user all relevant information required to decide if the payment should be made:

* Website details (URL, Title, Favicon,...)
* Amount
* Memo
* Fees

We should also allow the user to configure an allowance budget for the page.

Related component:
https://github.com/bumi/lightning-browser-extension/blob/master/src/app/components/ConfirmPayment/index.jsx

**Comment by chris-aeviator** [comment]
Status:

- [ ] Website URL --> (b)
- [ ] Website Title 
- [ ] Favicon
- [ ] Amount --> (a)
- [ ] Memo --> (c)
- [ ] Fees

![grafik](https://user-images.githubusercontent.com/11522213/115513175-11530100-a283-11eb-856f-eed15f1bb5f6.png)
    Fees
