### ISSUE TITLE
Command husky-run not found

### ISSUE THREAD

**Issue by chris-aeviator** [bumi/lightning-browser-extension#47]
hey @bumi is it possible that branches I take from you include a githook that tries to find husky.sh? I cannot base any new commit ontop of https://github.com/bumi/lightning-browser-extension/pull/37 

```
❯ git commit
error Command "husky-run" not found.
```

EDIT: I actually have husky.sh in .git

**Comment by bumi** [comment]
I was complaining about that in the chat also. :)
it is doing some linting in a pre-hook: https://github.com/bumi/lightning-browser-extension/blob/master/package.json#L33

I think this should not be a default and running `yarn install` should not automatically add git hooks. what do you think?
