### ISSUE TITLE
Password Screen - Configure vs Unlock

### ISSUE THREAD

**Issue by motorina0** [bumi/lightning-browser-extension#53]
The Password pop-up always asks to confirm the password.

The confirmation field should be required only when the password is set (or changed).
The password should not be entered twice for the unlock flow.

![image](https://user-images.githubusercontent.com/2951406/114373443-3e205d80-9b8b-11eb-9092-812766ab05ec.png)

**Comment by bumi** [comment]
The options page is currently one react component and it needs a password to encrypt the account configs. 
Adding that popup was the easiest to make sure that a password is always available. - I initially added that just to get started, we have to rethink the UX around that. 

Also an important note: the options page is completely independent of the popup / background script. So even if the account is currently unlocked in the background script, the options page does not know the password (the password is not kept in memory )

**Comment by motorina0** [comment]
fixed in #39

**Comment by chris-aeviator** [comment]
Shouldn't this represent a password protected settings page actually?

**Comment by bumi** [comment]
In my initial prototype I had it in to be able to encrypt account configs. 
It's your local computer why do you think the settings should be password protected?

**Comment by chris-aeviator** [comment]
Currently I'm able to reproduce the previously entered wallet address & admin macaroon by using the text-fields "cache" (delete the value and double click the field). I think nonetheless it's benefitial for OpSec to at least offer the possibility to password protect this settings page.

> It's your local computer
Computers are also often shared and I might not want to reveal my wallet address and especially not it's credentials to anyone with physical access to my computer.
