### ISSUE TITLE
Manifest v3

### ISSUE THREAD

**Issue by wlevchenko** [bumi/lightning-browser-extension#57]
Hello, why you are not using manifest v3 in your extension?

**Comment by bumi** [comment]
afaik only chrome supports manifest v3? 
But I also don't know enough about v3, yet. The big change will be the service workers instead of the background script.

**Comment by wlevchenko** [comment]
What do you think is it ok to use v2? Or in the future, it will be trouble with Chrome?

**Comment by chris-aeviator** [comment]
There's even people warning about v3 

> "WebExtensions are fully in the hands of Google, that can and will change it any time based on its own interests only. It is not a Web Standard."

http://www.glazman.org/weblog/dotclear/index.php?post/2019/01/23/WebExtensions-v3-considered-harmful

**Comment by wlevchenko** [comment]
Many thanks!
