### ISSUE TITLE
LNURL-Pay support

### ISSUE THREAD

**Issue by bumi** [bumi/lightning-browser-extension#6]
https://xn--57h.bigsun.xyz/lnurl-pay-flow.txt

https://github.com/fiatjaf/awesome-lnurl

**Comment by bumi** [comment]
@dylancom do you want to look into or maybe we work on this together? - we can discuss details then.

**Comment by dylancom** [comment]
@bumi yes, let's discuss details.

**Comment by bumi** [comment]
#141
