### ISSUE TITLE
Allowances page

### ISSUE THREAD

**Issue by bumi** [bumi/lightning-browser-extension#8]
Allowances will be a core feature that allows users to set budgets for specific sites.
The allowances page should allow users to see a list of all configured allowances with their details and allow users to configure those. 

Joule did some amazing work on that which is a great inspiration: 
https://medium.com/@wbobeirne/introducing-joule-allowances-2b08bec75e3a

**Comment by johnsBeharry** [comment]
NOTES
- not initiated by the publisher
- part of the payment flow
- i trust this publisher don't ask me again.
- set conditions for the allowance

**Comment by bumi** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/318/123111699-66ef8980-d43d-11eb-8cd1-ff1ec1945631.png">
(from the figma screens)
